services:

  postgres:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_USER: calvo
      POSTGRES_PASSWORD: calvo
      POSTGRES_DB: email_service
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  cache:
  pgdata: